import { Injectable } from "@angular/core";
import { HttpClient, HttpHeaders } from "@angular/common/http";

@Injectable({
  providedIn: "root",
})
export class CountriesService {
  url: string = "https://thongtindoanhnghiep.co/api/city";

  constructor(private http: HttpClient) {}
  dataProvince: any = [
    {
      Type: 1,
      SolrID: "/tien-giang",
      ID: 1,
      Title: "Tiền Giang",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 10727,
    },
    {
      Type: 1,
      SolrID: "/hung-yen",
      ID: 2,
      Title: "Hưng Yên",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 12121,
    },
    {
      Type: 1,
      SolrID: "/ha-noi",
      ID: 3,
      Title: "Hà Nội",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 277671,
    },
    {
      Type: 1,
      SolrID: "/tp-ho-chi-minh",
      ID: 4,
      Title: "TP Hồ Chí Minh",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 459958,
    },
    {
      Type: 1,
      SolrID: "/ca-mau",
      ID: 5,
      Title: "Cà Mau",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 10748,
    },
    {
      Type: 1,
      SolrID: "/dac-lac",
      ID: 6,
      Title: "Đắc Lắc",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 11103,
    },
    {
      Type: 1,
      SolrID: "/nam-dinh",
      ID: 7,
      Title: "Nam Định",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 11935,
    },
    {
      Type: 1,
      SolrID: "/quang-ninh",
      ID: 8,
      Title: "Quảng Ninh",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 19532,
    },
    {
      Type: 1,
      SolrID: "/dak-nong",
      ID: 9,
      Title: "Đắk Nông",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 5343,
    },
    {
      Type: 1,
      SolrID: "/da-nang",
      ID: 10,
      Title: "Đà Nẵng",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 40342,
    },
    {
      Type: 1,
      SolrID: "/hai-duong",
      ID: 11,
      Title: "Hải Dương",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 16591,
    },
    {
      Type: 1,
      SolrID: "/long-an",
      ID: 12,
      Title: "Long An",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 18774,
    },
    {
      Type: 1,
      SolrID: "/ben-tre",
      ID: 13,
      Title: "Bến Tre",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 8197,
    },
    {
      Type: 1,
      SolrID: "/dong-thap",
      ID: 14,
      Title: "Đồng Tháp",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 10489,
    },
    {
      Type: 1,
      SolrID: "/vinh-long",
      ID: 15,
      Title: "Vĩnh Long",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 7228,
    },
    {
      Type: 1,
      SolrID: "/kien-giang",
      ID: 16,
      Title: "Kiên Giang",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 17347,
    },
    {
      Type: 1,
      SolrID: "/tra-vinh",
      ID: 17,
      Title: "Trà Vinh",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 5602,
    },
    {
      Type: 1,
      SolrID: "/soc-trang",
      ID: 18,
      Title: "Sóc Trăng",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 6406,
    },
    {
      Type: 1,
      SolrID: "/bac-ninh",
      ID: 19,
      Title: "Bắc Ninh",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 17324,
    },
    {
      Type: 1,
      SolrID: "/thanh-hoa",
      ID: 20,
      Title: "Thanh Hoá",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 23965,
    },
    {
      Type: 1,
      SolrID: "/vung-tau",
      ID: 21,
      Title: "Vũng Tàu",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 18483,
    },
    {
      Type: 1,
      SolrID: "/dong-nai",
      ID: 22,
      Title: "Đồng Nai",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 41712,
    },
    {
      Type: 1,
      SolrID: "/binh-duong",
      ID: 23,
      Title: "Bình Dương",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 43722,
    },
    {
      Type: 1,
      SolrID: "/thai-nguyen",
      ID: 24,
      Title: "Thái Nguyên",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 9557,
    },
    {
      Type: 1,
      SolrID: "/thai-binh",
      ID: 25,
      Title: "Thái Bình",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 10806,
    },
    {
      Type: 1,
      SolrID: "/can-tho",
      ID: 26,
      Title: "Cần Thơ",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 19537,
    },
    {
      Type: 1,
      SolrID: "/nghe-an",
      ID: 27,
      Title: "Nghệ An",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 22902,
    },
    {
      Type: 1,
      SolrID: "/hue",
      ID: 28,
      Title: "Huế",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 9877,
    },
    {
      Type: 1,
      SolrID: "/binh-phuoc",
      ID: 29,
      Title: "Bình Phước",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 10963,
    },
    {
      Type: 1,
      SolrID: "/quang-nam",
      ID: 30,
      Title: "Quảng Nam",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 13907,
    },
    {
      Type: 1,
      SolrID: "/quang-ngai",
      ID: 31,
      Title: "Quảng Ngãi",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 10337,
    },
    {
      Type: 1,
      SolrID: "/ninh-thuan",
      ID: 32,
      Title: "Ninh Thuận",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 4858,
    },
    {
      Type: 1,
      SolrID: "/lao-cai",
      ID: 33,
      Title: "Lào Cai",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 6674,
    },
    {
      Type: 1,
      SolrID: "/hai-phong",
      ID: 34,
      Title: "Hải Phòng",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 44187,
    },
    {
      Type: 1,
      SolrID: "/an-giang",
      ID: 35,
      Title: "An Giang",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 12905,
    },
    {
      Type: 1,
      SolrID: "/phu-tho",
      ID: 36,
      Title: "Phú Thọ",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 9748,
    },
    {
      Type: 1,
      SolrID: "/tay-ninh",
      ID: 37,
      Title: "Tây Ninh",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 11210,
    },
    {
      Type: 1,
      SolrID: "/khanh-hoa",
      ID: 38,
      Title: "Khánh Hòa",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 22177,
    },
    {
      Type: 1,
      SolrID: "/phu-yen",
      ID: 39,
      Title: "Phú Yên",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 6539,
    },
    {
      Type: 1,
      SolrID: "/hoa-binh",
      ID: 40,
      Title: "Hòa Bình",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 6395,
    },
    {
      Type: 1,
      SolrID: "/tuyen-quang",
      ID: 41,
      Title: "Tuyên Quang",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 3703,
    },
    {
      Type: 1,
      SolrID: "/lai-chau",
      ID: 42,
      Title: "Lai Châu",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 3081,
    },
    {
      Type: 1,
      SolrID: "/hau-giang",
      ID: 43,
      Title: "Hậu Giang",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 5553,
    },
    {
      Type: 1,
      SolrID: "/lam-dong",
      ID: 44,
      Title: "Lâm Đồng",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 15331,
    },
    {
      Type: 1,
      SolrID: "/lang-son",
      ID: 45,
      Title: "Lạng Sơn",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 5745,
    },
    {
      Type: 1,
      SolrID: "/ha-nam",
      ID: 46,
      Title: "Hà Nam",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 7099,
    },
    {
      Type: 1,
      SolrID: "/bac-can",
      ID: 47,
      Title: "Bắc Cạn",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 2324,
    },
    {
      Type: 1,
      SolrID: "/binh-dinh",
      ID: 48,
      Title: "Bình Định",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 14080,
    },
    {
      Type: 1,
      SolrID: "/cao-bang",
      ID: 49,
      Title: "Cao Bằng",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 3551,
    },
    {
      Type: 1,
      SolrID: "/son-la",
      ID: 50,
      Title: "Sơn La",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 5352,
    },
    {
      Type: 1,
      SolrID: "/quang-binh",
      ID: 51,
      Title: "Quảng Bình",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 8411,
    },
    {
      Type: 1,
      SolrID: "/quang-tri",
      ID: 52,
      Title: "Quảng Trị",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 6949,
    },
    {
      Type: 1,
      SolrID: "/gia-lai",
      ID: 53,
      Title: "Gia Lai",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 9503,
    },
    {
      Type: 1,
      SolrID: "/bac-giang",
      ID: 54,
      Title: "Bắc Giang",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 11656,
    },
    {
      Type: 1,
      SolrID: "/ha-tinh",
      ID: 55,
      Title: "Hà Tĩnh",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 10711,
    },
    {
      Type: 1,
      SolrID: "/ninh-binh",
      ID: 56,
      Title: "Ninh Bình",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 7888,
    },
    {
      Type: 1,
      SolrID: "/binh-thuan",
      ID: 57,
      Title: "Bình Thuận",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 11237,
    },
    {
      Type: 1,
      SolrID: "/kon-tum",
      ID: 58,
      Title: "Kon Tum",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 4700,
    },
    {
      Type: 1,
      SolrID: "/vinh-phuc",
      ID: 59,
      Title: "Vĩnh Phúc",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 12785,
    },
    {
      Type: 1,
      SolrID: "/bac-lieu",
      ID: 60,
      Title: "Bạc Liêu",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 5459,
    },
    {
      Type: 1,
      SolrID: "/yen-bai",
      ID: 61,
      Title: "Yên Bái",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 4895,
    },
    {
      Type: 1,
      SolrID: "/dien-bien",
      ID: 62,
      Title: "Điện Biên",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 3166,
    },
    {
      Type: 1,
      SolrID: "/ha-giang",
      ID: 63,
      Title: "Hà Giang",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 4566,
    },
    {
      Type: 1,
      SolrID: "/chua-ro",
      ID: 64,
      Title: "Chưa rõ",
      STT: 0,
      Created: null,
      Updated: null,
      TotalDoanhNghiep: 61989,
    },
  ];
  allCountries(id) {
    return this.http.get(
      `https://thongtindoanhnghiep.co/api/city/${id}/district`
    );
  }
}
